### ISSUE TITLE
Use Micronaut application plugin to manage Micronaut version

### ISSUE THREAD

**Issue by hantsy** [micronaut-projects/micronaut-gradle-plugin#750] opened 2023-06-17 02:20 UTC
### Feature description

Similar to Spring boot, I wish Micronaut will use the application plugin to manage Micronaut version directly. 

The `micronautVersion` in the gradle.properties can not be recognized by Dependabot, etc. Use the application plugin can resolve this, also can not avoid the some conflicts from Micronaut version and the micronaut application plugin.

**Comment by melix** [comment] 2023-06-17 21:10
This is a duplicate of #681

**Closed by melix** 2023-06-17 21:10 UTC

**Comment by hantsy** [comment] 2023-06-18 02:00
@melix I checked the 681, do not think they are the same thing. Here, I means using one plugin to manage the Micronaut BOM dependencies and version **implicitly**, no need set it explicitly in the `gradle.property` or `lib.versions.toml`.
