### ISSUE TITLE
Docker native image doesn't respect the `micronaut.server.port` configured in `application.yml`

### ISSUE THREAD

**Issue by pgressa** [micronaut-projects/micronaut-gradle-plugin#246] opened 2021-09-10 16:40 UTC
### Expected Behavior

When having:
```
micronaut:
  application:
    name: demo
  server:
    port: 8081
```

I expect that when I start the docker native image build by `./gradlew dockerBuildNative` the application starts on port 8081

### Actual Behaviour

the application starts on 8080

### Steps To Reproduce

1. Generate application from launch.micronaut.io
2. Configure custom port in `application.yml`
3. Build docker native image `./gradlew dockerBuildNative`
4. run app `docker run -it demo:latest`

### Version

3.0.1

**Comment by melix** [comment] 2021-09-13 08:32
This is a duplicate of #243 : the issue isn't just about the application port: the whole `application.yml` file is ignored.

**Closed** 2021-09-13 09:37 UTC
