### ISSUE TITLE
micronaut-openapi-plugin: Provide modelNameSuffix property in OpenApiSpec.java

### ISSUE THREAD

**Issue by oliverkuntze** [micronaut-projects/micronaut-gradle-plugin#901] opened 2023-12-04 14:17 UTC
### Feature description

It would be great if we could have a more complete set of configuration properties for the OpenAPI codegen.

The properties in https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator-gradle-plugin/README.adoc could act as an example.

At least we need modelNameSuffix since we generate DAOs from the OpenAPI spec for the server side.

Would be great if we could have it in the 4.3.0 Release together with the fix for the client annotations, @altro3  :-)

By the way, the https://openapi-generator.tech/docs/generators/java-micronaut-server/ is lacking a config property "interfaceOnly" like the SpringCodegen. As a result java-micronaut-server java generator always creates an Application.java file which interferes with the Application.java in the actual code.

Thanks a lot in advance.

Cheers

Oliver

**Comment by altro3** [comment] 2023-12-05 08:14
@oliverkuntze What properties do you need? Transferring absolutely all the properties is a long process, there are too many of them and for each one you will have to describe the normal mapping with the gradle plugin property. But, you can do it yourself ;-) - being a contributor is not difficult ;-)

About "At least we need modelNameSuffix since we generate DAOs from the OpenAPI spec for the server side." - Tell us in more detail what you offer. because from this phrase one can assume many options. We need a more specific proposal.

About Application.java - this is not true, the plugin does not generate this class in any case. The generator itself can do this and the generateImplementationFiles property is responsible for this, but in the plugin it is always false . Therefore, I don’t understand how you managed to generate the Application.java file using the plugin

**Comment by melix** [comment] 2023-12-06 09:32
Micronaut OpenAPI and our build plugins doen't use the code generator from OpenAPI Tools anymore (it was designed for an older version of Micronaut and not maintained by us).

**Comment by oliverkuntze** [comment] 2023-12-06 13:04
Thanks for the insight!

**Comment by oliverkuntze** [comment] 2023-12-06 13:47
So I will 
- add modelNameSuffix + modelNamePrefix support in https://github.com/micronaut-projects/micronaut-gradle-plugin/blob/master/openapi-plugin
- add processing of the additionalProperties in https://github.com/micronaut-projects/micronaut-openapi/blob/master/openapi-generator/src/main/java/io/micronaut/openapi/generator/AbstractMicronautJavaCodegen.java
correct?

**Comment by melix** [comment] 2023-12-06 14:24
Mostly correct I think. You'll need to add support for the new properties in the code generator as you mentioned, but also expose them in a type-safe manner in the appropriate builders (see for example https://github.com/micronaut-projects/micronaut-openapi/blob/master/openapi-generator/src/main/java/io/micronaut/openapi/generator/JavaMicronautClientOptionsBuilder.java).

There's also the Maven plugin which uses this API: https://github.com/micronaut-projects/micronaut-maven-plugin/tree/master/micronaut-maven-plugin/src/main/java/io/micronaut/maven/openapi

(basically any change to the OpenAPI generator has to be reflected to both the Gradle and Maven plugins)

**Comment by oliverkuntze** [comment] 2024-02-06 11:11
Just a brief sign of life. We now have a corresponding story prioritized in our backlog. :-)

**Comment by altro3** [comment] 2024-02-11 09:58
@oliverkuntze I have added support for prefixes and suffixes. After the release of micronaut-openapi 6.6.0, we will be able to add these properties to the plugin. I have already created a draft with changes

**Closed** 2024-02-26 08:55 UTC

**Comment by oliverkuntze** [comment] 2024-04-02 15:32
That's great news! Thanks a lot!
