### ISSUE TITLE
v3.0.0 doesn't work in multi module project if you use `io.micronaut.application` plugin and `micronaut-test-junit5` dependency

### ISSUE THREAD

**Issue by alejandropg** [micronaut-projects/micronaut-gradle-plugin#315] opened 2021-11-25 09:51 UTC
### Expected Behavior

I don't know if I'm doing something wrong, but in a multi module Gradle project, if in some module you use plugin `io.micronaut.application` and implementation dependency with `io.micronaut.test:micronaut-test-junit5` or `org.junit.jupiter:junit-jupiter-engine` the build fails because looks like the plugin try to apply twice the testing framework.

### Actual Behaviour

The build fails because looks like the plugin try to apply twice the testing framework.

The problem looks like in file `MicronautLibraryPlugin` lines `186` and `184`, when the plugin tries to detect the testing framework and apply it twice. It's like a "reentrant"??? 

But this behavior only occurs when you use the plugin `io.micronaut.application`. If you use the plugin `io.micronaut.library` all works fine.

```
Caused by: java.lang.IllegalStateException: The value for this property is final and cannot be changed any further.
        at org.gradle.api.internal.provider.AbstractProperty$FinalizedValue.beforeMutate(AbstractProperty.java:489)
        at org.gradle.api.internal.provider.AbstractProperty.assertCanMutate(AbstractProperty.java:263)
        at org.gradle.api.internal.provider.AbstractProperty.setSupplier(AbstractProperty.java:212)
        at org.gradle.api.internal.provider.DefaultProperty.set(DefaultProperty.java:71)
        at org.gradle.api.tasks.testing.Test.useTestFramework(Test.java:979)
        at org.gradle.api.tasks.testing.Test.useJUnitPlatform(Test.java:1049)
        at org.gradle.api.tasks.testing.Test.useJUnitPlatform(Test.java:1032)
----->  at io.micronaut.gradle.MicronautLibraryPlugin.lambda$null$3(MicronautLibraryPlugin.java:186)
        at org.gradle.configuration.internal.DefaultUserCodeApplicationContext$CurrentApplication$1.execute(DefaultUserCodeApplicationContext.java:123)
        at org.gradle.api.internal.DefaultCollectionCallbackActionDecorator$BuildOperationEmittingAction$1.run(DefaultCollectionCallbackActionDecorator.java:110)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:29)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:26)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.run(DefaultBuildOperationRunner.java:47)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:68)
        at org.gradle.api.internal.DefaultCollectionCallbackActionDecorator$BuildOperationEmittingAction.execute(DefaultCollectionCallbackActionDecorator.java:107)
        at org.gradle.api.internal.collections.CollectionFilter$1.execute(CollectionFilter.java:59)
        at org.gradle.api.internal.DefaultDomainObjectCollection.all(DefaultDomainObjectCollection.java:159)
        at org.gradle.api.internal.tasks.DefaultRealizableTaskCollection.all(DefaultRealizableTaskCollection.java:224)
        at org.gradle.api.internal.DefaultDomainObjectCollection.withType(DefaultDomainObjectCollection.java:201)
----->  at io.micronaut.gradle.MicronautLibraryPlugin.lambda$apply$4(MicronautLibraryPlugin.java:184)
        at org.gradle.configuration.internal.DefaultUserCodeApplicationContext$CurrentApplication$1.execute(DefaultUserCodeApplicationContext.java:123)
        at org.gradle.configuration.internal.DefaultListenerBuildOperationDecorator$BuildOperationEmittingAction$1.run(DefaultListenerBuildOperationDecorator.java:152)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:29)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:26)
```

I tried to apply the dependency `micronaut-test-junit5` in the specific module (outside of `buildSrc`) and the problem it's the same.

Also, I tried to apply or not apply explicitly the `tasks.named('test') { useJUnitPlatform() }` and the problem it's the same.

### Steps To Reproduce

In the example project <https://github.com/alejandropg/gradle-multimodule-micronaut> run:

```bash
gradle build
```

And see the complete stacktrace with:

```bash
gradle build --stacktrace
```

### Environment Information

- Mac Pro M1
- macOs 12.0.1
- Kotlin 1.6.0
- micronaut-gradle-plugin 3.0.0
- Micronaut 3.2.0

### Example Application

https://github.com/alejandropg/gradle-multimodule-micronaut

### Version

Micronaut Plugin 3.0.0, and Micronaut 3.2.0

**Comment by ilopmar** [comment] 2021-11-25 16:24
I think this is a duplicate of #296. @alejandropg there is a workaround in that issue, please try it.

**Comment by alejandropg** [comment] 2021-11-25 17:16
Hi @ilopmar , nice to talk with you ☺️ 👋

Looks like that is the same problem. I'm sorry because before adding this I searched for related issues but didn't find anything (I searched by "multi-module" 😓).

I tested the workaround and works fine 👍
In my example I used:

```groovy
tasks.named('test') {
    useJUnitPlatform()
}
```
and the workaround is to use:
```groovy
tasks.withType(Test).configureEach {
	useJUnitPlatform()
}
```

Thanks a lot!

**Comment by ilopmar** [comment] 2021-11-26 07:45
Hi Alex! I'm glad you finally switch to Gradle :smiley: 

I'll close this as a duplicate.

**Closed by ilopmar** 2021-11-26 07:45 UTC

**Comment by alejandropg** [comment] 2021-11-26 10:06
hehehe, I'm just exploring 😜
It's nice the `buildSrc` to create plugins with a shared configuration that you can use to "decorate" the different modules 👍 (but I'm much more fan of Micronaut than Gradle 😉😉)

Ok with the close of this issue 👍 (anyway the Gradle solution I think is not a real solution to the problem and will fail again y Gradle 7.4)

Thanks for all @ilopmar ! 👏👏👏👏
