### ISSUE TITLE
Latest Plugin no longer compatible with AdoptOpenJDK

### ISSUE THREAD

**Issue by osh-onstructive** [micronaut-projects/micronaut-gradle-plugin#226] opened 2021-06-29 09:01 UTC
Using the latest plugin version, and all versions before that (2.0.1, 2.0.0, 1.5.3 & 1.5.2), there is an issue with the creation of the group and user when using AdoptOptenJDK:

```
Step 5/11 : COPY layers/application.jar /home/app/application.jar
 ---> a28635710d42
Step 6/11 : RUN test -e /usr/sbin/groupadd && groupadd -r app && adduser -g app app && chown -R app:app /home/app || true
 ---> Running in 317860c6429c
Option g is ambiguous (gecos, gid, group)
adduser [--home DIR] [--shell SHELL] [--no-create-home] [--uid ID]
[--firstuid ID] [--lastuid ID] [--gecos GECOS] [--ingroup GROUP | --gid ID]
[--disabled-password] [--disabled-login] [--add_extra_groups]
[--encrypt-home] USER
   Add a normal user

adduser --system [--home DIR] [--shell SHELL] [--no-create-home] [--uid ID]
[--gecos GECOS] [--group | --ingroup GROUP | --gid ID] [--disabled-password]
[--disabled-login] [--add_extra_groups] USER
   Add a system user

adduser --group [--gid ID] GROUP
addgroup [--gid ID] GROUP
   Add a user group

addgroup --system [--gid ID] GROUP
   Add a system group

adduser USER GROUP
   Add an existing user to an existing group

general options:
  --quiet | -q      don't give process information to stdout
  --force-badname   allow usernames which do not match the
                    NAME_REGEX[_SYSTEM] configuration variable
  --extrausers      uses extra users as the database
  --help | -h       usage message
  --version | -v    version number and copyright
  --conf | -c FILE  use FILE as configuration file

Removing intermediate container 317860c6429c
 ---> 3363edfed9b9
Step 7/11 : RUN test -e /usr/sbin/addgroup && addgroup app && adduser -G app app -D && chown -R app:app /home/app || true
 ---> Running in 006f6b367336
addgroup: The group `app' already exists.
Removing intermediate container 006f6b367336
 ---> aff8070b8a42
```

We are currently using adoptopenjdk/openjdk15:jre-15.0.2_7 as our base image.

I have tried the latest plugin, and all in-between, but this issue seems to arise in 1.5.1.

**Comment by ilopmar** [comment] 2021-06-29 10:46
Duplicate of #225

**Closed by ilopmar** 2021-06-29 10:46 UTC
Labels: closed: duplicate
